%YAML:1.0
dataset_dir: "/home/dcbin/cpp_ws/vslam_ws/vo_frontend/rgbd_dataset"

camera.fx: 517.3
camera.fy: 516.5
camera.cx: 325.1
camera.cy: 249.7
camera.depth_scale: 5000.0

num_features: 500 # ORB求解的特征点数
num_inliers_min: 50 # 最小内点数
keyframe_min_rot: 0.1
keyframe_min_trans: 0.1 
level_pyramid: 8 # 图像金字塔层数
scale_factor: 1.2 # 图像金字塔尺度因子
match_ratio: 0.7 
num_lost_max: 10 # 最大丢失次数